browser:
  browserName: chrome
  windowMaximized: true
  windowHeadless: false
  webElementTimeOut: 15

environment:
  env1:
    envName: test
    active: true
    appUrl: http://146.59.32.4/index.php
